### ISSUE TITLE
Support the `selector` dark mode strategy

### ISSUE THREAD

**Issue by tommy-mitchell** [JavierM42/tailwind-mode-aware-colors#10]
Tailwind recommends using `selector` over `class`: https://tailwindcss.com/docs/dark-mode#supporting-system-preference-and-manual-selection

From what I can tell, `selector` is basically `class` that falls back to `media` when the selector isn't present.

Types reference: https://github.com/tailwindlabs/tailwindcss/blob/d86fd0bb5b69c9aa5c75d4e78f8fe78969d6ff50/types/config.d.ts#L69-L83

**Comment by tommy-mitchell** [comment]
@JavierM42 I'm not quite sure that's the correct implementation? `class` is still supported as a strategy, and it seems like `root.classList.add("light")` doesn't change the mode-aware colors.

**Comment by JavierM42** [comment]
`class="light"` is not the intended usage, as per the docs, so that's expected behavior. You choose a selector for the alternative (dark) mode, and the absence of said selector means default (light) mode.

Unless you want to reverse the names and set dark as the default and light as the alternative, then you'd set ['selector', '.light'] as the dark mode strategy.

---

What do you mean about `class` still being supported? In base Tailwind, it _is_ still supported, but only as a legacy configuration, because all of its use cases can be solved with `selector`. I think they'll remove it in v4. In the context of this library, I chose not to support it in favor of simplicity, which resulteed in a breaking change and thus a major version bump.

If you were to use v2.0.1 of the package and nevertheless specify `'class'` as the dark mode strategy, it should not work as expected: the `class` value won't be recognized, the plugin will assume `media`, but base TailwindCSS will use `class`, resulting in unexpected behavior. The `variant` strategy isn't supported by this library either.

---

If something's still not working, I'm here to help :)
