### ISSUE TITLE
Feature request: Add support for textColor, backgroundColor, outlineColor, and borderColor

### ISSUE THREAD

**Issue by PretzelJohn** [JavierM42/tailwind-mode-aware-colors#3]
The plugin currently only supports `theme.colors` and `extend.theme.colors`, but it would be very useful to also have:

- `theme.textColor` and `extend.theme.textColor`
- `theme.backgroundColor` and `extend.theme.backgroundColor`
- `theme.borderColor` and `extend.theme.borderColor`
- `theme.outlineColor` and `extend.theme.outlineColor`

Why? So I can use `text-primary` instead of `text-text-primary` in my classnames, or `bg-surface` instead of `bg-background-surface`. It helps simplify the naming scheme when working with existing design systems. Thanks!

**Comment by JavierM42** [comment]
That's an interesting use case. I've personally never used the scoped themes, but it seems reasonable to support this feature since Tailwind does.

I put together an initial implementation and it seems to be working, but writing readable tests for this will take me some time. I'll see what I can do.

**Comment by JavierM42** [comment]
Released v1.3.0 with support for the scoped themes.

Don't hesitate to open another issue if something doesn't work, as I wrote a couple of automated tests and only did some light manual testing.

**Comment by PretzelJohn** [comment]
Thank you so much for adding this! It works great, no issues. You're the best!
